spring:
  application:
    name: SRMS-Backend

  datasource:
    url: jdbc:mysql://localhost:3306/srms_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Raghav@0103
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  mail:
    host: smtp.gmail.com
    port: 587
    username: rp5410900@gmail.com
    password: "iedbnmhhvpruvyko"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: SRMS_SECRET_KEY_REPLACE_WITH_A_LONG_RANDOM_STRING_MIN_32_CHARS
  expiration: 36000000

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs

server:
  port: 8080